export const GENERATION_SERVER_MAX_DURATION = 300;

export const LEARN_OUTLINE_CLIENT_TIMEOUT_MS = 305_000;
export const LEARN_MISSION_CLIENT_TIMEOUT_MS = 310_000;
export const LEARN_READY_CLIENT_TIMEOUT_MS = 65_000;

export const COMPOSER_ENHANCE_CLIENT_TIMEOUT_MS = 65_000;
export const COMPOSER_ENHANCE_SERVER_MAX_DURATION = 60;

export {
  PRACTICE_BATCH_CLIENT_TIMEOUT_MS,
  PRACTICE_BLUEPRINT_CLIENT_TIMEOUT_MS,
  PRACTICE_SERVER_MAX_DURATION,
} from '@/lib/learning/practice/bounds';
